[Dialogs]
UserInfo=0
FeatureInfo1=1
SingleDirectory=1
InstallationType=0
FeatureTree=0
License=0
License2=1
NICertificate=0
WinFastStartup=1
ConfirmStart=1
End=1

[Distribution]
Title=1
GUID={5FDEF958-8E2E-4ACE-B2AC-D8E30E752E2E}
PackageGUID={4F76F222-B99D-408F-BC2F-897AE408FF0D}
Version=1.0.2
IDPath=nidist.id
Has64bitPart=1

[EndDialog]
Readme=5;30,50,330,150;static

[Files]
License2TextFile0009=NI;license\NI Released License Agreement - English.rtf
License2TextFile0010=NI;license\NI Released License Agreement - Spanish.rtf
License2TextFile0016=NI;license\NI Released License Agreement - Italian.rtf
License2TextFile0007=NI;license\NI Released License Agreement - German.rtf
License2TextFile0012=NI;license\NI Released License Agreement - French.rtf
License2TextFile0017=NI;license\NI Released License Agreement - Japanese.rtf
License2TextFile0018=NI;license\NI Released License Agreement - Korean.rtf
License2TextFile2052=NI;license\NI Released License Agreement - Simplified Chinese.rtf

[Graphics]
TopBar=IDB_TOPSTRIP,IDB_LARGETOPSTRIP
FullScreen=IDB_FULLSCREEN,IDB_LARGEFULLSCREEN

[InitProgress]
left=55
top=165
right=340
bottom=179
red=206
green=203
blue=173

[InstallLevels]
Default=100

[Localization]
Languages=9
ForceLanguage=9
CustomRes0009=supportfiles\customResource0009.dll
StandardLangXfm0007=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0007.mst
StandardLangXfm0012=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0012.mst
StandardLangXfm0017=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0017.mst
StandardLangXfm0018=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0018.mst
StandardLangXfm2052=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans2052.mst

[Merged]
Path=supportfiles\merged.cab

[OS]
VersionNTMin=10,0,0,0,0
VersionNTMax=

[Settings]
WelcomeAutoAdvance=1

[SingleDirectoryDialog]
DirText1=4
DirText2=7
Dir1=INSTALLDIR.MDF100
Dir1EditLabel=8
Dir2=NIDIR64
Dir2EditLabel=9

[WinFastStartupDialog]
CheckboxDefaultState=1

[Strings]
WelcomeTitle=2;15,20,260,45
WelcomeText=3;15,55,260,115

[Utilities]

[Parts]
LV2021runtime.msi=
LV2021rtdnet.msi=
activex.msi=
activex64.msi=
nicurl.msi=
nicurl64.msi=
dep_framework64.msi=
ni_error_report64.msi=
NIER_Interface.msi=
NIER_Interface64.msi=
LVRT_NBFifo64_2021.msi=
logos.msi=
logos64.msi=
NIWebServer_LVRTE64.msi=
MatlabInterface.msi=
MatlabInterface64.msi=
MDFSupport.msi=
mDNSResponder.msi=
mDNSResponder_W64.msi=
MetaUninstaller.msi=
mkl.msi=
mkl64.msi=
mkl.msi<2>=
mkl64.msi<2>=
MSIProperties.msi=
MSIProperties64.msi=
MStudioCW3DGraph.msi=
VC2015Core.msi=
VC2015-32Wrapper.msi=
VC2015-64Wrapper.msi=
PythonInterface.msi=
PythonInterface64.msi=
nisvcloc.msi=
NISysLogUtils.msi=
tdms.msi=
tdms64.msi=
NITraceEngine.msi=
NITraceEngine64.msi=
ni_ssl.msi=
ni_ssl64.msi=
DotNet462.msi=
DotNet462_Wrapper.msi=
CertInstaller_Wrapper.msi=
LogosXT.msi=
LogosXT64.msi=
niauth.msi=
niauth64.msi=
NI_SysStatePub.msi=
NI_SysStatePub64.msi=
ssl_LV64RTEsupp.msi=
EULADepot2.msi=
KillBit.msi=
KillBit64.msi=
install.msi=
[LV2021runtime.msi]
Path=bin\p29\LV2021runtime.msi
Volume=1
ProductCode={1FD331BB-AC24-4120-A8EF-DC2078AD4843}
ProductId={1FD331BB-AC24-4120-A8EF-DC2078AD4843}
LangXfm0007=bin\p29\LV2021runtime_deu.mst
LangXfm0012=bin\p29\LV2021runtime_fra.mst
LangXfm0017=bin\p29\LV2021runtime_jpn.mst
LangXfm0018=bin\p29\LV2021runtime_kor.mst
LangXfm2052=bin\p29\LV2021runtime_chs.mst
[LV2021rtdnet.msi]
Path=bin\p29\LV2021rtdnet.msi
Volume=1
ProductCode={CCDB236D-5C31-4F3E-BFE8-277FEF5A2D92}
[activex.msi]
Path=bin\p22\activex.msi
Volume=1
ProductCode={EB6C9E35-CBA2-4C2B-8958-55EA6F0EA707}
ProductId={EB6C9E35-CBA2-4C2B-8958-55EA6F0EA707}
LangXfm0007=bin\p22\activex_deu.mst
LangXfm0012=bin\p22\activex_fra.mst
LangXfm0017=bin\p22\activex_jpn.mst
LangXfm0018=bin\p22\activex_kor.mst
LangXfm2052=bin\p22\activex_chs.mst
[activex64.msi]
Path=bin\p22\activex64.msi
Volume=1
ProductCode={52E7C292-9986-4E2F-9273-7F180451D403}
LangXfm0007=bin\p22\activex64_deu.mst
LangXfm0012=bin\p22\activex64_fra.mst
LangXfm0017=bin\p22\activex64_jpn.mst
LangXfm0018=bin\p22\activex64_kor.mst
LangXfm2052=bin\p22\activex64_chs.mst
[nicurl.msi]
Path=bin\p20\nicurl.msi
Volume=1
ProductCode={E4776418-A44C-4A5E-A5F6-3A4B710A2FE6}
ProductId={E4776418-A44C-4A5E-A5F6-3A4B710A2FE6}
[nicurl64.msi]
Path=bin\p20\nicurl64.msi
Volume=1
ProductCode={86CD3677-7A4A-4F28-8230-BE81AAEF0119}
[dep_framework64.msi]
Path=bin\p6\NI_De00\dep_framework64.msi
Volume=1
ProductCode={3AE96134-78CA-4E89-8CB6-0CECDBB6AAEC}
ProductId={3AE96134-78CA-4E89-8CB6-0CECDBB6AAEC}
[ni_error_report64.msi]
Path=bin\p17\ni_err64\ni_error_report64.msi
Volume=1
ProductCode={506342C4-1FEC-44D8-B6CD-A0EAE2A61D57}
ProductId={506342C4-1FEC-44D8-B6CD-A0EAE2A61D57}
[NIER_Interface.msi]
Path=bin\p14\NIER_Interface.msi
Volume=1
ProductCode={E0DAF96D-BF67-46CD-87A7-45E7E12A8074}
ProductId={E0DAF96D-BF67-46CD-87A7-45E7E12A8074}
[NIER_Interface64.msi]
Path=bin\p14\NIER_Interface64.msi
Volume=1
ProductCode={07EE79B8-D8C0-4DB5-A88D-1473EF205B99}
[LVRT_NBFifo64_2021.msi]
Path=bin\p9\LVRT_00\LVRT_NBFifo64_2021.msi
Volume=1
ProductCode={EF4CD21E-6601-4ABD-B392-343C4C649660}
ProductId={EF4CD21E-6601-4ABD-B392-343C4C649660}
LangXfm0007=bin\p9\LVRT_00\LVRT_NBFifo64_2021_deu.mst
LangXfm0012=bin\p9\LVRT_00\LVRT_NBFifo64_2021_fra.mst
LangXfm0017=bin\p9\LVRT_00\LVRT_NBFifo64_2021_jpn.mst
LangXfm0018=bin\p9\LVRT_00\LVRT_NBFifo64_2021_kor.mst
LangXfm2052=bin\p9\LVRT_00\LVRT_NBFifo64_2021_chs.mst
[logos.msi]
Path=bin\p27\logos.msi
Volume=1
ProductCode={195D8F29-2704-44BD-A978-57A0382327E5}
ProductId={195D8F29-2704-44BD-A978-57A0382327E5}
LangXfm0007=bin\p27\logos_deu.mst
LangXfm0012=bin\p27\logos_fra.mst
LangXfm0017=bin\p27\logos_jpn.mst
LangXfm0018=bin\p27\logos_kor.mst
LangXfm2052=bin\p27\logos_chs.mst
[logos64.msi]
Path=bin\p27\logos64.msi
Volume=1
ProductCode={C3AEF5D6-43D1-4BAA-892F-D114CA599302}
LangXfm0007=bin\p27\logos64_deu.mst
LangXfm0012=bin\p27\logos64_fra.mst
LangXfm0017=bin\p27\logos64_jpn.mst
LangXfm0018=bin\p27\logos64_kor.mst
LangXfm2052=bin\p27\logos64_chs.mst
[NIWebServer_LVRTE64.msi]
Path=bin\p19\LabVI00\NIWebServer_LVRTE64.msi
Volume=1
ProductCode={D6607787-DC07-4743-9A9C-FDCCB8713D1F}
ProductId={D6607787-DC07-4743-9A9C-FDCCB8713D1F}
[MatlabInterface.msi]
Path=bin\p10\MatlabInterface.msi
Volume=1
ProductCode={549A0179-F0EB-4855-BB1F-2CE75128687C}
ProductId={549A0179-F0EB-4855-BB1F-2CE75128687C}
[MatlabInterface64.msi]
Path=bin\p10\MatlabInterface64.msi
Volume=1
ProductCode={53C07548-DB6B-4B11-A757-B63657F132D6}
[MDFSupport.msi]
Path=bin\p25\MDF\MDFSupport.msi
Volume=1
ProductCode={D37DC7B4-F7DD-45D9-8CD8-30B4893E811E}
ProductId={D37DC7B4-F7DD-45D9-8CD8-30B4893E811E}
[mDNSResponder.msi]
Path=bin\p13\mDNSResponder.msi
Volume=1
ProductCode={67A55F1F-BA21-47AA-9AFE-0444E506742F}
ProductId={67A55F1F-BA21-47AA-9AFE-0444E506742F}
[mDNSResponder_W64.msi]
Path=bin\p13\mDNSResponder_W64.msi
Volume=1
ProductCode={88A2AFB2-587A-4158-9132-B05F4A4C38F3}
[MetaUninstaller.msi]
Path=bin\p0\MU\MetaUninstaller.msi
Volume=1
ProductCode={5836AF9F-665E-43CD-A8DC-BEFC5946F5A3}
ProductId={5836AF9F-665E-43CD-A8DC-BEFC5946F5A3}
[mkl.msi]
Path=bin\p26\mkl.msi
Volume=1
ProductCode={6A8A28A0-4568-4718-A3E7-F951C191602B}
ProductId={6A8A28A0-4568-4718-A3E7-F951C191602B}
LangXfm0007=bin\p26\mkl_deu.mst
LangXfm0012=bin\p26\mkl_fra.mst
LangXfm0017=bin\p26\mkl_jpn.mst
LangXfm0018=bin\p26\mkl_kor.mst
LangXfm2052=bin\p26\mkl_chs.mst
[mkl64.msi]
Path=bin\p26\mkl64.msi
Volume=1
ProductCode={C8AE1FF1-C898-4171-B03B-94D5E487C2D8}
LangXfm0007=bin\p26\mkl64_deu.mst
LangXfm0012=bin\p26\mkl64_fra.mst
LangXfm0017=bin\p26\mkl64_jpn.mst
LangXfm0018=bin\p26\mkl64_kor.mst
LangXfm2052=bin\p26\mkl64_chs.mst
[mkl.msi<2>]
Path=bin\p28\mkl.msi
Volume=1
ProductCode={A12FB799-41BF-4A9A-98F2-2FE4F333B718}
ProductId={A12FB799-41BF-4A9A-98F2-2FE4F333B718}
LangXfm0007=bin\p28\mkl_deu.mst
LangXfm0012=bin\p28\mkl_fra.mst
LangXfm0017=bin\p28\mkl_jpn.mst
LangXfm0018=bin\p28\mkl_kor.mst
LangXfm2052=bin\p28\mkl_chs.mst
[mkl64.msi<2>]
Path=bin\p28\mkl64.msi
Volume=1
ProductCode={E32B7385-4770-4AED-B9DE-5A079EC82D07}
LangXfm0007=bin\p28\mkl64_deu.mst
LangXfm0012=bin\p28\mkl64_fra.mst
LangXfm0017=bin\p28\mkl64_jpn.mst
LangXfm0018=bin\p28\mkl64_kor.mst
LangXfm2052=bin\p28\mkl64_chs.mst
[MSIProperties.msi]
Path=bin\p16\MetaUtils\MSIProperties.msi
Volume=1
ProductCode={84F53873-9E42-4A30-B0A7-60A2C6B182DD}
ProductId={84F53873-9E42-4A30-B0A7-60A2C6B182DD}
[MSIProperties64.msi]
Path=bin\p16\MetaUtils\MSIProperties64.msi
Volume=1
ProductCode={343AD57E-0D92-4510-BA7E-62789C4B840B}
[MStudioCW3DGraph.msi]
Path=bin\p30\MStudioCW3DGraph.msi
Volume=1
ProductCode={A9B6FC03-1277-40DF-A475-32389FD27883}
ProductId={A9B6FC03-1277-40DF-A475-32389FD27883}
[VC2015Core.msi]
Path=bin\p3\VC2015Core.msi
Volume=1
ProductCode={AFC999BB-F270-46EF-B748-AE755EC75322}
ProductId={AFC999BB-F270-46EF-B748-AE755EC75322}
[VC2015-32Wrapper.msi]
Path=bin\p3\VC2015-32Wrapper.msi
Volume=1
ProductCode={992AB883-9A1B-4E64-A7D8-010D8A067B91}
[VC2015-64Wrapper.msi]
Path=bin\p3\VC2015-64Wrapper.msi
Volume=1
ProductCode={851DF324-5346-4D0E-AD29-F8321FFF8BEF}
[PythonInterface.msi]
Path=bin\p11\PythonInterface.msi
Volume=1
ProductCode={75216B26-952C-4AC1-A442-1D10933696EB}
ProductId={75216B26-952C-4AC1-A442-1D10933696EB}
[PythonInterface64.msi]
Path=bin\p11\PythonInterface64.msi
Volume=1
ProductCode={F939A3BD-A77D-4C1A-A304-CB111DB7C212}
[nisvcloc.msi]
Path=bin\p15\svcloc\nisvcloc.msi
Volume=1
ProductCode={2BAD7C38-1B6F-46C6-B663-224BE7A9A4B8}
ProductId={2BAD7C38-1B6F-46C6-B663-224BE7A9A4B8}
LangXfm0007=bin\p15\svcloc\nisvcloc_deu.mst
LangXfm0012=bin\p15\svcloc\nisvcloc_fra.mst
LangXfm0017=bin\p15\svcloc\nisvcloc_jpn.mst
LangXfm0018=bin\p15\svcloc\nisvcloc_kor.mst
LangXfm2052=bin\p15\svcloc\nisvcloc_chs.mst
[NISysLogUtils.msi]
Path=bin\p4\NISys00\NISysLogUtils.msi
Volume=1
ProductCode={40B51053-A9E9-4B0F-A92E-985B6770E80B}
ProductId={40B51053-A9E9-4B0F-A92E-985B6770E80B}
[tdms.msi]
Path=bin\p23\tdms.msi
Volume=1
ProductCode={B14D1FE6-2A7F-404F-8DC6-A6512139FB06}
ProductId={B14D1FE6-2A7F-404F-8DC6-A6512139FB06}
LangXfm0007=bin\p23\tdms_deu.mst
LangXfm0012=bin\p23\tdms_fra.mst
LangXfm0017=bin\p23\tdms_jpn.mst
LangXfm0018=bin\p23\tdms_kor.mst
LangXfm2052=bin\p23\tdms_chs.mst
[tdms64.msi]
Path=bin\p23\tdms64.msi
Volume=1
ProductCode={9DDFE52B-134D-4E4A-A56A-418BC55C3A12}
LangXfm0007=bin\p23\tdms64_deu.mst
LangXfm0012=bin\p23\tdms64_fra.mst
LangXfm0017=bin\p23\tdms64_jpn.mst
LangXfm0018=bin\p23\tdms64_kor.mst
LangXfm2052=bin\p23\tdms64_chs.mst
[NITraceEngine.msi]
Path=bin\p8\NITraceEngine.msi
Volume=1
ProductCode={5A656240-393B-4579-B9E1-D5B45E75ACEC}
ProductId={5A656240-393B-4579-B9E1-D5B45E75ACEC}
[NITraceEngine64.msi]
Path=bin\p8\NITraceEngine64.msi
Volume=1
ProductCode={3C6FA667-BE0A-4D47-81F1-04CCAA628911}
[ni_ssl.msi]
Path=bin\p24\ni_ssl.msi
Volume=1
ProductCode={3FFCB06E-2075-4D82-8C79-C8E6EDDED7C1}
ProductId={3FFCB06E-2075-4D82-8C79-C8E6EDDED7C1}
LangXfm0007=bin\p24\ni_ssl_deu.mst
LangXfm0012=bin\p24\ni_ssl_fra.mst
LangXfm0017=bin\p24\ni_ssl_jpn.mst
LangXfm0018=bin\p24\ni_ssl_kor.mst
LangXfm2052=bin\p24\ni_ssl_chs.mst
[ni_ssl64.msi]
Path=bin\p24\ni_ssl64.msi
Volume=1
ProductCode={B3D1CE80-B9E9-401E-8C72-45D16C1F3913}
LangXfm0007=bin\p24\ni_ssl64_deu.mst
LangXfm0012=bin\p24\ni_ssl64_fra.mst
LangXfm0017=bin\p24\ni_ssl64_jpn.mst
LangXfm0018=bin\p24\ni_ssl64_kor.mst
LangXfm2052=bin\p24\ni_ssl64_chs.mst
[DotNet462.msi]
Path=bin\p2\DotNet462.msi
Volume=1
ProductCode={E6406D9C-7E60-4819-B647-41C549D25CCC}
ProductId={E6406D9C-7E60-4819-B647-41C549D25CCC}
[DotNet462_Wrapper.msi]
Path=bin\p2\DotNet462_Wrapper.msi
Volume=1
ProductCode={5B4608CC-F2AD-4A5D-A3F6-D69C80A37794}
LangXfm0007=bin\p2\DotNet462_Wrapper_deu.mst
LangXfm0012=bin\p2\DotNet462_Wrapper_fra.mst
LangXfm0017=bin\p2\DotNet462_Wrapper_jpn.mst
LangXfm0018=bin\p2\DotNet462_Wrapper_kor.mst
LangXfm2052=bin\p2\DotNet462_Wrapper_chs.mst
[CertInstaller_Wrapper.msi]
Path=bin\p2\CertInstaller_Wrapper.msi
Volume=1
ProductCode={EF5A307F-CC70-4420-B53E-534657DF3D2F}
[LogosXT.msi]
Path=bin\p21\LogosXT.msi
Volume=1
ProductCode={FD58B244-C5D6-4842-8940-6F315FCF717F}
ProductId={FD58B244-C5D6-4842-8940-6F315FCF717F}
[LogosXT64.msi]
Path=bin\p21\LogosXT64.msi
Volume=1
ProductCode={51C5BAB2-2099-4513-B0F6-BBAC2D60739F}
[niauth.msi]
Path=bin\p18\niauth.msi
Volume=1
ProductCode={24EFB5DF-D49A-401D-9C65-777411CD4B25}
ProductId={24EFB5DF-D49A-401D-9C65-777411CD4B25}
[niauth64.msi]
Path=bin\p18\niauth64.msi
Volume=1
ProductCode={78FE788F-4B52-4757-A1BD-7D13F48E1A1A}
[NI_SysStatePub.msi]
Path=bin\p12\NI_SysStatePub.msi
Volume=1
ProductCode={082C3EB6-2F71-478A-B9CD-F3FCDF6C94AA}
ProductId={082C3EB6-2F71-478A-B9CD-F3FCDF6C94AA}
[NI_SysStatePub64.msi]
Path=bin\p12\NI_SysStatePub64.msi
Volume=1
ProductCode={6DAE339A-36FA-4B5D-98B5-51C1A65D298D}
[ssl_LV64RTEsupp.msi]
Path=bin\p5\ssl64RTE\ssl_LV64RTEsupp.msi
Volume=1
ProductCode={83F1F87B-0DE8-40EB-8BDA-AE16A3BC54C1}
ProductId={83F1F87B-0DE8-40EB-8BDA-AE16A3BC54C1}
[EULADepot2.msi]
Path=bin\p1\EULADepot2.msi
Volume=1
ProductCode={99D3B9D7-C0E0-41A5-8945-CF13FDE63435}
ProductId={99D3B9D7-C0E0-41A5-8945-CF13FDE63435}
[KillBit.msi]
Path=bin\p7\KillBit.msi
Volume=1
ProductCode={64ECB814-3A6A-4E48-9D2F-D6C2EDD725B7}
ProductId={64ECB814-3A6A-4E48-9D2F-D6C2EDD725B7}
[KillBit64.msi]
Path=bin\p7\KillBit64.msi
Volume=1
ProductCode={3BD1EEE5-2B3D-428A-9CAB-4DE4A38070C4}
[install.msi]
Path=bin\dp\install.msi
Volume=1
ProductCode={16F8B417-7CAE-4029-B0B9-74C2D0B512F0}
ProductId={16F8B417-7CAE-4029-B0B9-74C2D0B512F0}
[LicenseTypes]
LicenseType2=NIStandardReleased
LicenseType3=Apache20
LicenseType4=Boost
LicenseType5=BSD3Clause
LicenseType6=MatLabBSD
LicenseType7=CryptoPP
LicenseType8=DotNet462
LicenseType9=FreeType
LicenseType10=GPL
LicenseType11=LGPL
LicenseType12=LLVM
LicenseType13=MARS
LicenseType14=MicrosoftPublicLicense
LicenseType15=MSVC 2015 Runtime
LicenseType16=MIT
LicenseType17=MIT-X-YAJL
LicenseType18=MIT-X
LicenseType19=Mozilla20
LicenseType20=SIL
LicenseType21=NICTA
LicenseType22=OpenSSL
LicenseType23=UPX
LicenseType24=wxWindows
LicenseType25=WordNet21
LicenseType26=zlib
[LicenseType2]
IsDisplayedAlone=0
IsThirdParty=0
IsHideInMetaSuite=0
[LicenseType3]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType4]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType5]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType6]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType7]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType8]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType9]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType10]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType11]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType12]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType13]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType14]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType15]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType16]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType17]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType18]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType19]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType20]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType21]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType22]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType23]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType24]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType25]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType26]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[DotNetPreinstall]
DotNet40Preinstall=1
DotNet40Path=bin\p2\NDP462-KB3151800-x86-x64-AllOS-ENU.exe
DotNet40Version=4.6.1590.0
DotNet40ProductCode={5B4608CC-F2AD-4A5D-A3F6-D69C80A37794}
[SilentInstallRequirements]
MustAcceptLicenses=1
[MDF]
MDFVersion=21.0.0.74
HasPatchSupport=0
DevPartSection=install.msi
